parameters:
- name: 

trigger:
  batch: true
  - master
  - releases/*

resources:
  repositories:
  - repository: self

stages:
- stage: Build
  jobs:
    - job: BuildPython
      steps:
      - task: UsePythonVersion@0
         inputs:
           versionSpec: '$(pythonVersion)'
           displayName: 'Use Python $(pythonVersion)'
      - script: |       

- stage: Deploy
  dependsOn: Build
  displayName: Deploy to Azure
  env:
    MY_MAPPED_ENV_VAR: $(mySecret)
  jobs:
    pool:
      vmImage: 'ubuntu-latest'
  - template: ./deploy.yml
    parameters:
      Environment: AT
      ServiceConnection: SFA-DAS-DevTest-ARM

